<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "worldcup2"
 *
 * Auto generated by Extension Builder 2021-03-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Place WM and EM Bets',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Jörg Velletti',
    'author_email' => 'typo3@velletti.de',
    'state' => 'alpha',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.2',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
