services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  JVE\Worldcup2\:
    resource: '../Classes/*'

  JVE\Worldcup2\Command\UpdateRanking:
    tags:
      - name: 'console.command'
        command: 'worldcup2:updateranking'
